apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent
      imagePullPolicy: Always
    - name: docker-dind
      image: docker:18.05-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
    - name: build
      image: us.gcr.io/stoked-monitor-275907/build_packer_template_slave:latest
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
  volumes:
    - name: dind-storage
      emptyDir: {}
